version: 2

sources:
  - name: raw
    description: ""
    tables:
      - name: orders
        description: ""
        columns:
          - name: id
            data_type: varchar
            description: ""
          - name: customer
            data_type: varchar
            description: ""
          - name: ordered_at
            data_type: timestamp
            description: ""
          - name: store_id
            data_type: varchar
            description: ""
          - name: subtotal
            data_type: bigint
            description: ""
          - name: tax_paid
            data_type: bigint
            description: ""
          - name: order_total
            data_type: bigint
            description: ""

      - name: products
        description: ""
        columns:
          - name: sku
            data_type: varchar
            description: ""
          - name: name
            data_type: varchar
            description: ""
          - name: type
            data_type: varchar
            description: ""
          - name: price
            data_type: bigint
            description: ""
          - name: description
            data_type: varchar
            description: ""

      - name: customers
        description: ""
        columns:
          - name: id
            data_type: varchar
            description: ""
          - name: name
            data_type: varchar
            description: ""

      - name: items
        description: ""
        columns:
          - name: id
            data_type: varchar
            description: ""
          - name: order_id
            data_type: varchar
            description: ""
          - name: sku
            data_type: varchar
            description: ""

      - name: stores
        description: ""
        columns:
          - name: id
            data_type: varchar
            description: ""
          - name: name
            data_type: varchar
            description: ""
          - name: opened_at
            data_type: timestamp
            description: ""
          - name: tax_rate
            data_type: double
            description: ""

      - name: supplies
        description: ""
        columns:
          - name: id
            data_type: varchar
            description: ""
          - name: name
            data_type: varchar
            description: ""
          - name: cost
            data_type: bigint
            description: ""
          - name: perishable
            data_type: boolean
            description: ""
          - name: sku
            data_type: varchar
            description: ""

